[logger]
level = "debug"

[storage]
type = "memory"
driver = "postgres"
conn = "host=127.0.0.1 port=5432 user=calendar_user password=pass4calendarusr dbname=calendar_db sslmode=disable"

[net]
host = "127.0.0.1"
port = 8082