version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    networks:
      main:
        aliases:
          - db
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
networks:
  main:
