version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - db.env
    networks:
      main:
        aliases:
          - db
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
  api:
    image: calendarapi:develop
    depends_on:
      - db
    networks:
      main:
        aliases:
          - api
  rabbit:
    image: rabbitmq:3-alpine
    env_file:
      - rabbit.env
    networks:
      main:
        aliases:
          - rabbit
networks:
  main:
