[logger]
level = "debug"

[storage]
type = "sql"
driver = "postgres"
conn = "host=127.0.0.1 port=5432 user=calendar_user password=pass4calendarusr dbname=calendar_db sslmode=disable"

[api]
type = "grpc"
host = "127.0.0.1"
port = 8082

[queue]
host = "127.0.0.1"
port = 5672
user = "calendar_user"
password = "password"