version: "3"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: Adminpassword321
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/calendar/data
      - ./init/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      main:
        aliases:
          - db
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      main:
        aliases:
          - adminer
  proxy:
    image: nginx:latest
    volumes:
      - ./templates/nginx:/etc/nginx/templates
    ports:
      - "80:80"
    links:
      - adminer:adminer
    depends_on:
      - adminer
    networks:
      main:
        aliases:
          - proxy
volumes:
  database:
networks:
  main:
